name: ci-java-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  checkout-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml